services:
  - type: web
    name: instagram-checker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python Arman_newfile.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: NUM_THREADS
        value: "30"
      - key: PYTHON_VERSION
        value: "3.11.0"
    healthCheckPath: /health
